### ISSUE TITLE
Suggestion: add config option for data model tier count cost

### ISSUE THREAD

**Issue by WhiskeeDev** [CafeteriaGuild/DeepMobLearning-Refabricated#124]
When Sim was it's own mod, simulations did not deduct tier count (data) from attuned data model.

In the new version, each simulation deducts one, as [seen on line 54 of the DataModelUtil](https://github.com/CafeteriaGuild/DeepMobLearning-Refabricated/blob/122d3f1f15f2ca83c0a444f345ec84f3a69143be/simulacrum/src/main/kotlin/dev/nathanpb/dml/simulacrum/util/DataModelUtil.kt#L54).

My suggestion would be to add a config option for this value, so server owners can adjust to higher or lower whole integer values.

If this is agreed on, I'd also recommend adding config to other similar values related to sims, wherever best applicable.

**Comment by NathanPB** [comment]
Thanks for suggesting, we are working on that 

https://discord.com/channels/707435077679841350/737793698984755372/1074515751307841638

**Comment by Luligabi1** [comment]
On the newest release (coming in a few minutes, hopefully), we've added the `dataBonus` config option, defaulted to `1` (the old behavior of adding data). 
Once we move over to a proper registry for data model categories, we could add specific costs for each tier of each category. But for now, let's keep it straight forward, eh? 😅
