### ISSUE TITLE
The Energy Update

### ISSUE THREAD

**Issue by Luligabi1** [CafeteriaGuild/DeepMobLearning-Refabricated#133]
> If you have any suggestions, please hop on our [Discord](https://discord.com/invite/G4PjhEf) and tell us there - it's more likely to be heard there.

### First off, this update plans to solve two issues:

- Glitch Armor is not competitive with other similar armors, mostly due to pristine matter being used far too quickly, even after the values were halved;
- Energy usage is inconsistent and, when required, the mod has no built-in generator to generate it, relying on third-party mods.

### To fix these, we plan to implement the following:

- [x] Data Synthesizer 
    - [x] Consumes a Data Model's data for energy. To avoid abusing it with a Simulation Chamber, all data models that have been used by a simulation chamber will be flagged, rendering then unable to be used by the Data Synthesizer;
    - [x] GUI aesthetic;
    - [x] Block aesthetic;
    - [x] Sound
    - This generator's energy would be common, being the same used by other mods and lower-tiered machines.
- [x] Loot Fabricator rework
    - [x] Use energy;
- [x] Matter condenser rework
    - [x] Now condenses Pristine Matter to generate PE (Pristine Energy);
    - [x] PE is used exclusively to charge Glitch Equipment (more on the next point).

**Glitch Armor Overhaul:**    
- [x] Modular effects no longer consume data;
- [x] Instead, it's consumed from the armor's PE, a far less valuable resource (as 1 pristine matter = PE in the thousands);
- [x] No longer has tiers that data models have to comply, only the data model's tier + required PE is necessary.

**Misc and supporting content:**

- [x] **Glitch Sword:**
*A Netherite sword infused with a Glitch Ingot*
    - [x] Charged with common energy;
    - [x] Mobs killed with it grant double data;
    - [x] System Glitch takes double damage against it;
    - [x] Cannot be enchanted;
    - [x] Texture

- [x] **Energy Octahedron:** 
    - [x] Allows moving energy between different machines;
    - [x] Recipe

- [x] **Pristine Energy Cube:** 
    - [x] Allows moving PE energy between different Matter Condensers;
    - [x] Distributes PE energy for all equipped pieces;
    - [x] Recipe
    
- [x] Disruption
*A disruption is a randomly generated structure that disappear soon after the core (pretty much a fancy chest) is opened, allowing mod specific-loot to be obtained.*
    - [x] Disruption Core's functionalities;
    - [x] Fading Glitched Tile;
    - [x] Loottable;
    - [x] Worldgen.    
    
 - [x] Glitched Tile set  
     - [x] Glitched Tile;  
     - [x] Glitched Stairs;  
     - [x] Glitched Slab;  
     - [x] Glitched Wall;
     - [x] Verify if recipes, loot tables, tags, etc are all in place.
     
**Other tasks:**
- [x] Divide config per module (i.e. `.minecraft/config/dml-refabricated/simulacrum.json`)

**Comment by NathanPB** [comment]
:open_mouth:
