### ISSUE TITLE
Cannot retrieve grave upon death during trial

### ISSUE THREAD

**Issue by aoshibba** [CafeteriaGuild/DeepMobLearning-Refabricated#141]
aof6 1.10.1
deepmoblearning-refabricated-0.5.12-BETA+1.19.2
You're in Grave Danger 1.4.9

I've built a trial area high up in the sky around y 120-50 ish
while going through a skeleton trial(the highest difficulty one) I died and spawned somewhere quite far.
I used /home tp (base) command to get near to a waystone
and then used the waystone to get to another waystone which is few blocks away from the trial area
(I bridged out a few blocks from the area)
After I arrived at my grave I found out that I couldn't pick up my grave, I tried lots of weird combinations of things.
Then I tried to break trial keystone with my hands and it didn't break, as if I was trying to break a protected block.
The same was for blocks around it, such as the trial area ground blocks, I even used pickaxes.

**Comment by Luligabi1** [comment]
Did the trial fail normally (you should see a chat message if so) or did all mobs just despawn? It's likely the trial was on some weird state. Either way, I'm thinking of adding a tag of blocks that can be broken during trials regardless of state, so any graves can be retrieved without much hassle

**Comment by aoshibba** [comment]
After dying I kind of instantly responded at my spawn point(not sure if I
pressed respawn or I instantly respawned).

The spawnpoint was far from my base so when I came back the mobs were gone,
possibly due to the chunk being unloaded and the despawn radius thing.

At the time I was hurrying to retrieve my grave and didn't pay much
attention to the chat messages so I'm not sure if there were additional
messages apart from trial failed. But I think I saw the trial failed
message, although I'm not a 100percent sure...

I also noticed that you could check these chats from the prism launcher,
which I used to launch the mod pack and the game. However it was after a
few turning on and off so I wasn't able to check the previous chat logs...

It seems like there are some other people who are having similar(but not
entirely same) problems and I hope it gets fixed soon

Also thank you for replying :)

2023년 9월 5일 (화) 오전 1:49, Luiz Feikes ***@***.***>님이 작성:

**Comment by Luligabi1** [comment]
Seems similar to #91, I'll take a look into it.

**Comment by aoshibba** [comment]
Yeah this one seems quite similar to the problem I'm having.
I hope the worldedit thing would work on my server haha...

Thank you for all your effort!!

2023년 9월 5일 (화) 오전 2:10, Luiz Feikes ***@***.***>님이 작성:

**Comment by Luligabi1** [comment]
I've added the trial grief whitelist tag, hopefully other modders will add their graves to it eventually.
As for the trial issue - I'll keep tracking it on #91. Thanks for reporting!
