### ISSUE TITLE
Partial Incompatibility with MC Dungeons Weapons

### ISSUE THREAD

**Issue by chronosacaria** [CafeteriaGuild/DeepMobLearning-Refabricated#54]
Hi NathanPB,

I hope that you are well. 

I got a report of some issues of some of my crossbows not working in certain modpacks and I was finally able to narrow down the issue to DML-Refabricated. However, I am not 100% why. I did notice that there is a mixin related to crossbow reloading. If you want to test it out, you can load both of our mods together and try to shoot the Corrupted Crossbow, for example. It will have the loading animation, but will not actually load a bolt.

Please let me know if there is anything that I can do on my end.

Take care!
chronosacaria

**Comment by NathanPB** [comment]
Hey, thanks for reaching me. I will check this up later, running a bit low on time lately.

I do have a (very cursed) mixin on crossbows to make it load faster, sure this is the problem. I will try to test this out when I have some time

**Comment by chronosacaria** [comment]
Thank you, so much, mate! And thanks for such a quick response!

**Comment by NathanPB** [comment]
@chronosacaria what do those crossbows that are not working have in special?

**Comment by chronosacaria** [comment]
That is the weird part, I couldn't find anything in common with them. I really don't know why it was this in particular. I know that it can't be arbitrary but it sure feels that way, ya know?

**Comment by NathanPB** [comment]
Do you have your mod published anywhere that I could import on gradle? I'm still now sure how to use the curseforge's maven thing

**Comment by NathanPB** [comment]
Crossbows that have ``24f`` or less of draw speed are the ones that the bug occurs, I will keep investigating to figure out why

**Comment by chronosacaria** [comment]
Sorry, I just saw these. I'm on vacation, so my response time is a bit delayed. As far as publishing, apart from on GitHub I've not got it published anywhere because I honestly don't understand how the whole maven thing works yet

**Comment by chronosacaria** [comment]
Hey @NathanPB! I know that it has been a while, but we might have been able to get this issue resolved? Kluzzio has taken a look at the mixin and was able to change the second `@ModifyVariable` to a `@ModifyArg` and we were able to get the crossbows shooting again whilst everything else appeared to work still. Kluzzio will be submitting what they did as a PR so you can take a look at it. Please let us know if this is something that works as I would love to see this issue resolved.

**Comment by NathanPB** [comment]
@chronosacaria sure, I received the PR, I'm just checking some stuff before getting this merged
