### ISSUE TITLE
Cut armor effect costs by half everywhere

### ISSUE THREAD

**Issue by NathanPB** [CafeteriaGuild/DeepMobLearning-Refabricated#62]
The only reason why this is difficult is because it won't take any effect in existing configurations

**Comment by Luligabi1** [comment]
Remember to also give each pristine matter a individual loot fabricator value on the config

> The only reason why this is difficult is because it won't take any effect in existing configuration
if this isn't accomplished, do all these changes on the 1.19 update.

**Comment by Luligabi1** [comment]
No longer necessary due to #133
